---
title: "Global STP Analysis - S. pistillata"
author: "Matt"
date: "November 16, 2014"
output: html_document
---

### Load required libraries

```{r setup}
library("phyloseq")
library("ggplot2")
library("plyr")
library("vegan")
library("grid")
library("directlabels")
library("knitr")
setwd("./data")
```

# Relative abundance of pocillopora damicornis otus bar plot

```{r, fig.width = 10}
microSubRelFiltPdamiFilt = filter_taxa(microSubRelFiltPdami, function(x) mean(x) > 1e-2, TRUE)
pdamiBar <- plot_bar(microSubRelFiltPdamiFilt, fill="Genus", title='Pocillopora damicornis')
pdamiBar + facet_wrap(~site, scales="free")
```

Interestingly, these P.damicornis samples have less Endozoicomonas than the closely related P.verrucosa. 

Take a look at the different Endozoicomonas OTUs

```{r, fig.width = 10, fig.height = 6}
microSubRelFiltPdamiFiltEndo = subset_taxa(microSubRelFiltPdamiFilt, Genus=='Endozoicomonas(100)')
PdamiBarEndo <- plot_bar(microSubRelFiltPdamiFiltEndo, fill="Genus", title='P.verr')
PdamiBarEndo + facet_wrap(~site, scales='free')

# add coloring for different Endozoicomonas OTUs
tax_table(microSubRelFiltPdamiFiltEndo) <- cbind(tax_table(microSubRelFiltPdamiFiltEndo), Strain=taxa_names(microSubRelFiltPdamiFiltEndo))
myranks = c("Genus", "Strain")
mylabels = apply(tax_table(microSubRelFiltPdamiFiltEndo)[, myranks], 1, paste, sep="", collapse="_")
tax_table(microSubRelFiltPdamiFiltEndo) <- cbind(tax_table(microSubRelFiltPdamiFiltEndo), catglab=mylabels)
microSubRelFiltPdamiFiltEndoFilt = filter_taxa(microSubRelFiltPdamiFiltEndo, function(x) mean(x) > 1e-2, TRUE)
plot_bar(microSubRelFiltPdamiFiltEndo, fill="catglab", title='Pocillopora damicornis') +
  facet_wrap(~site, scales='free')

microSubRelFiltPdamiFiltEndoFilt = filter_taxa(microSubRelFiltPdamiFiltEndo, function(x) mean(x) > 1e-5, TRUE)
plot_bar(microSubRelFiltPdamiFiltEndoFilt, fill="catglab", title='Pocillopora damicornis') +
  facet_wrap(~site, scales='free')
```
