---
title: "Global STP Analysis - S. pistillata"
author: "Matt"
date: "November 16, 2014"
output: html_document
---

### Load required libraries

```{r setup}
library("phyloseq")
library("ggplot2")
library("plyr")
library("vegan")
library("grid")
library("directlabels")
library("knitr")
library("clustsig")
library("ellipse")
setwd("./data")
opts_knit$set(root.dir = "./data", fig.keep='high')
```

# Relative abundance of Pocillopora verrucosa otus bar plot

```{r, fig.width = 10}
microSubRelFiltPverrFilt = filter_taxa(microSubRelFiltPverr, function(x) mean(x) > 1e-2, TRUE)
pverrBar <- plot_bar(microSubRelFiltPverrFilt, fill="Genus", title='Pocillopora verrucosa')
pverrBar + facet_wrap(~site, scales="free")
```

Lots of Endozoicomonas - maybe even more abundant than in our Stylophora pistillata samples. 

Take a look at the different Endozoicomonas OTUs

```{r, fig.width = 10, fig.height = 6}
microSubRelFiltPverrFiltEndo = subset_taxa(microSubRelFiltPverrFilt, Genus=='Endozoicomonas(100)')
pverrBarEndo <- plot_bar(microSubRelFiltPverrFiltEndo, fill="Genus", title='P.verr')
pverrBarEndo + facet_wrap(~site, scales='free')

# add coloring for different Endozoicomonas OTUs
tax_table(microSubRelFiltPverrFiltEndo) <- cbind(tax_table(microSubRelFiltPverrFiltEndo), Strain=taxa_names(microSubRelFiltPverrFiltEndo))
myranks = c("Genus", "Strain")
mylabels = apply(tax_table(microSubRelFiltPverrFiltEndo)[, myranks], 1, paste, sep="", collapse="_")
tax_table(microSubRelFiltPverrFiltEndo) <- cbind(tax_table(microSubRelFiltPverrFiltEndo), catglab=mylabels)
microSubRelFiltPverrFiltEndoFilt = filter_taxa(microSubRelFiltPverrFiltEndo, function(x) mean(x) > 1e-2, TRUE)
plot_bar(microSubRelFiltPverrFiltEndo, fill="catglab", title='Pocillopora verrucosa') +
  facet_wrap(~site, scales='free')

microSubRelFiltPverrFiltEndoFilt = filter_taxa(microSubRelFiltPverrFiltEndo, function(x) mean(x) > 1e-5, TRUE)
plot_bar(microSubRelFiltPverrFiltEndoFilt, fill="catglab", title='Pocillopora verrucosa') +
  facet_wrap(~site, scales='free')
```